# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1588101508);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1588273085);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1588275552);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1588101466);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1588101285);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1588273205);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1582054057);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.migration.version", 42);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1588273057736");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1588276657736");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180315145708");
user_pref("browser.slowStartup.averageTime", 1900);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20180315145708");
user_pref("browser.startup.homepage_override.mstone", "52.7.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 1);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20200430);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1582054119666");
user_pref("datareporting.sessions.current.activeTicks", 10);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1697);
user_pref("datareporting.sessions.current.main", 200);
user_pref("datareporting.sessions.current.sessionRestored", 1756);
user_pref("datareporting.sessions.current.startTime", "1588275520984");
user_pref("datareporting.sessions.current.totalTime", 55);
user_pref("datareporting.sessions.currentIndex", 8);
user_pref("datareporting.sessions.previous.3", "{\"s\":1588101252945,\"a\":22,\"t\":164,\"c\":true,\"m\":852,\"fp\":3175,\"sr\":3775}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1588101435198,\"a\":4,\"t\":37,\"c\":true,\"m\":243,\"fp\":1690,\"sr\":1958}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1588101476701,\"a\":6,\"t\":51,\"c\":true,\"m\":270,\"fp\":2095,\"sr\":2183}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1588273053361,\"a\":6,\"t\":229,\"c\":true,\"m\":330,\"fp\":2581,\"sr\":2654}");
user_pref("datareporting.sessions.previous.7", "{\"s\":1588275255398,\"a\":0,\"t\":12,\"c\":true,\"m\":153,\"fp\":1697,\"sr\":1758}");
user_pref("datareporting.sessions.prunedIndex", 2);
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.859121");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{\"aushelper@mozilla.org\":{\"version\":\"2.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"e10srollout@mozilla.org\":{\"version\":\"1.10\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true,\"dependencies\":[],\"hasEmbeddedWebExtension\":false}}");
user_pref("extensions.databaseSchema", 19);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318};support@lastpass.com;");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "51set1");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:52.7.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "52.7.0");
user_pref("extensions.lastPlatformVersion", "52.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"aushelper@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"2.0\",\"st\":1521126626000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.10\",\"st\":1521126626000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib64/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1521126627000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1521126627000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"52.7.0\",\"st\":1521126626000}}}");
user_pref("idle.lastDailyNotification", 1588273126);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1582054120);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20180315145708");
user_pref("media.gmp-manager.lastCheck", 1588273116);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1588273126);
user_pref("places.history.expiration.transient_current_max_pages", 122334);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1588273043);
user_pref("services.blocklist.clock_skew_seconds", 41);
user_pref("services.blocklist.gfx.checked", 1588273043);
user_pref("services.blocklist.last_update_seconds", 1588273043);
user_pref("services.blocklist.plugins.checked", 1588273043);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1586745331);
user_pref("toolkit.startup.last_success", 1588275521);
user_pref("toolkit.telemetry.cachedClientID", "5944de58-ffaf-4bda-a0bd-849af4787416");
user_pref("toolkit.telemetry.previousBuildID", "20180315145708");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
